channels:
  '#126-grading': 'CTMLHUD25'
  '#126-grading-notifications': 'C01B1735FCK'
  '#random': 'CTLAUK751'
  '#226-grading-notifications': 'C048UC8GAKZ'

sources:
  - course: 'COS126'
    period: 'F2022'
    channel: '#126-grading-notifications'
    assignments:
      - name: 'Hello'
        start: '2022-09-14'
        end: '2022-09-18'
      - name: 'Loops'
        start: '2022-09-21'
        end: '2022-09-25'
      - name: 'NBody'
        start: '2022-09-28'
        end: '2022-10-15'
      - name: 'Functions'
        start: '2022-10-05'
        end: '2022-10-15'
      - name: 'Sierpinski'
        start: '2022-10-12'
        end: '2022-10-30'
      - name: 'Classifier'
        start: '2022-11-02'
        end: '2022-11-08'
  - course: 'COS226'
    period: 'F2022'
    channel: '#226-grading-notifications'
    assignments:
      - name: 'Percolation'
        start: '2022-09-05'
        end: '2022-09-19'
      - name: 'Queues'
        start: '2022-09-20'
        end: '2022-09-26'
      - name: 'Autocomplete'
        start: '2022-09-27'
        end: '2022-10-03'
      - name: 'KdTrees'
        start: '2022-10-04'
        end: '2022-10-31'
      - name: 'Wordnet'
        start: '2022-11-01'
        end: '2022-11-14'
      - name: 'SeamCarving'
        start: '2022-11-15'
        end: '2022-11-21'
      - name: 'BurrowsWheeler'
        start: '2022-11-22'
        end: '2022-12-05'
