sources:
  - course: 'COS126'
    period: 'F2022'
    channel: '#126-grading-notifications'
    assignments:
      - name: 'Hello'
        dates: '2022-09-14 - 2022-09-18'
      - name: 'Loops'
        dates: '2022-09-21 - 2022-09-25'
      - name: 'NBody'
        dates: '2022-09-28 - 2022-10-13'
      - name: 'Functions'
        dates: '2022-10-05 - 2022-10-13'
      - name: 'Sierpinski'
        dates: '2022-10-12 - 2022-10-16'
