channels:
  '#126-grading': 'CTMLHUD25'
  '#126-grading-notifications': 'C01B1735FCK'
  '#random': 'CTLAUK751'
  '#226-grading-notifications': 'C048UC8GAKZ'

messages:
  notification: '*{assignment}*: {done:.2%} done
    ({finalized} finalized, {drafts} drafts, {unclaimed} left to grade)'
  recent_graders: 'Graders who recently finalized: {graders}'
  deadline: '*{assignment}*: All submissions should now be finalized
    ({deadline} deadline)'

sources:
  - course: 'COS126'
    period: 'S2023'
    channel: '#126-grading-notifications'
    assignments:
      - name: 'Hello'
        start: '2023-02-07'
        end: '2023-02-15'
        deadline: '2023-02-10 23:59'
      - name: 'Loops'
        start: '2023-02-14'
        end: '2023-02-22'
        deadline: '2023-02-17 23:59'
      - name: 'NBody'
        start: '2023-02-21'
        end: '2023-03-01'
        deadline: '2023-02-24 23:59'
      - name: 'Functions'
        start: '2023-02-28'
        end: '2023-03-22' # extended for late submissions
        deadline: '2023-03-03 23:59'
      - name: 'Sierpinski'
        start: '2023-03-07'
        end: '2023-03-22' # extended for spring break
        deadline: '2023-03-10 23:59'
      # recess
      # we don't grade Hamming
      - name: 'Classifier'
        start: '2023-03-28'
        end: '2023-04-05'
        deadline: '2023-03-31 23:59'
      - name: 'Guitar'
        start: '2023-04-04'
        end: '2023-04-12'
        # started late, so deadline is extended by one day
        deadline: '2023-04-08 23:59'
      - name: 'Markov'
        start: '2023-04-11'
        end: '2023-04-19'
        deadline: '2023-04-14 23:59'
      - name: 'TSPP'
        start: '2023-04-18'
        end: '2023-04-26'
        deadline: '2023-04-21 23:59'
      - name: 'Programming Exam 2'
        start: '2023-04-26'
        end: '2023-05-03'
  - course: 'COS226'
    period: 'S2023'
    channel: '#226-grading-notifications'
    assignments:
      # start date is the day before grading starts
      # end date is the day after grading ends
      - name: 'Percolation'
        start: '2023-02-07'
        end: '2023-02-13'
      - name: 'Queues'
        start: '2023-02-14'
        end: '2023-02-19'
      - name: 'Autocomplete'
        start: '2023-02-28'
        end: '2023-03-04'
      - name: 'Kd Tree'
        start: '2023-03-28'
        end: '2023-04-01'
      - name: 'WordNet'
        start: '2023-04-04'
        end: '2023-04-10'
      - name: 'Seam Carving'
        start: '2023-04-18'
        end: '2023-04-24'
      - name: 'Burrows'
        start: '2023-05-02'
        end: '2023-05-06'
