channels:
  '#126-grading': 'CTMLHUD25'
  '#126-grading-notifications': 'C01B1735FCK'
  '#random': 'CTLAUK751'
  '#226-grading-notifications': 'C048UC8GAKZ'

messages:
  notification: '*{assignment}*: {done:.2%} done
    ({finalized} finalized, {drafts} drafts, {unclaimed} left to grade)'
  recent_graders: 'Graders who recently finalized: {graders}'
  deadline: '*{assignment}*: All submissions should now be finalized
    ({deadline} deadline)'

sources:
  - course: 'COS126'
    period: 'F2022'
    channel: '#126-grading-notifications'
    assignments:
      - name: 'Hello'
        start: '2022-09-14'
        end: '2022-09-18'
      - name: 'Loops'
        start: '2022-09-21'
        end: '2022-09-25'
      - name: 'NBody'
        start: '2022-09-28'
        end: '2022-10-15'
      - name: 'Functions'
        start: '2022-10-05'
        end: '2022-10-15'
      - name: 'Sierpinski'
        start: '2022-10-12'
        end: '2022-10-30'
      - name: 'Classifier'
        start: '2022-11-02'
        end: '2022-11-08'
      - name: 'Guitar'
        start: '2022-11-09'
        end: '2022-11-15'
      - name: 'Markov'
        start: '2022-11-16'
        end: '2022-11-22'
  - course: 'COS226'
    period: 'F2022'
    channel: '#226-grading-notifications'
    assignments:
      - name: 'Percolation'
        start: '2022-09-21'
        end: '2022-10-05'
      - name: 'Queues'
        start: '2022-09-28'
        end: '2022-10-12'
      - name: 'Autocomplete'
        start: '2022-10-05'
        end: '2022-10-19'
      - name: 'Kd Tree'
        start: '2022-11-02'
        end: '2022-11-16'
      - name: 'WordNet'
        start: '2022-11-16'
        end: '2022-11-30'
      - name: 'Seam Carving'
        start: '2022-11-30'
        end: '2022-12-14'
      - name: 'Burrows'
        start: '2022-12-07'
        end: '2022-12-21'
