channels:
  '#126-grading': 'CTMLHUD25'
  '#126-grading-notifications': 'C01B1735FCK'
  '#random': 'CTLAUK751'

sources:
  - course: 'COS126'
    period: 'F2022'
    channel: '#126-grading-notifications'
    assignments:
      - name: 'Hello'
        start: '2022-09-14'
        end: '2022-09-18'
      - name: 'Loops'
        start: '2022-09-21'
        end: '2022-09-25'
      - name: 'NBody'
        start: '2022-09-28'
        end: '2022-10-15'
      - name: 'Functions'
        start: '2022-10-05'
        end: '2022-10-15'
      - name: 'Sierpinski'
        start: '2022-10-12'
        end: '2022-10-30'
      - name: 'Classifier'
        start: '2022-11-02'
        end: '2022-11-08'
