on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # Runs every half hour on Wednesday, Thursday, and Friday.
    # https://crontab.guru/#0,30_*_*_*_3,4,5
    - cron: "0,30 * * * 3,4,5"
    # Runs every 3rd hour on Sunday, Monday, Tuesday, and Saturday.
    # https://crontab.guru/#0_0/3_*_*_0,1,2,6
    - cron: "0 0/3 * * 0,1,2,6"

name: UTAs Slack Bot Notifications
jobs:
  update-logs:
    name: UTAs Slack Bot Notifications
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      pull-requests: write
      repository-projects: write
    env:
      PIPENV_VENV_IN_PROJECT: "enabled"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Check pipenv cache before installing dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ./.venv # since we know that .venv is gonna be created in the current working directory
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv

      - name: Install requirements
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          touch Pipfile
          pipenv install --deploy --dev --verbose

      - name: Get data and send notification
        env:
          CODEPOST_API_KEY: ${{ secrets.CODEPOST_API_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}
        run: |
          pipenv run python ./utas_slack_bot.py

      - name: Commit generated logs 🚀
        uses: EndBug/add-and-commit@v9
        with:
          message: "Commit updated data"
          add: "./data/*"
          cwd: "."
          force: true
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
