on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Runs every half hour on Wednesday, Thursday, and Friday.
    # https://crontab.guru/#0,30_*_*_*_3,4,5
    - cron: '0,30 * * * 3,4,5'
    # Temp value of midnight on January 1
    - cron: '0 0 1 1 *'

name: UTAs Slack Bot Notifications
jobs:
  update-logs:
    name: UTAs Slack Bot Notifications
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Check pipenv cache before installing dependencies
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          touch Pipfile
          pipenv install --deploy --dev

      - name: Get data and send notification
        env:
          CODEPOST_API_KEY: ${{ secrets.CODEPOST_API_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}
        run: |
          pipenv run python ./utas_slack_bot.py

      - name: Commit generated logs 🚀
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Commit updated data'
          add: './data/*/* ERRORS.txt'
          cwd: '.'
          force: true
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
